label:
  restricted_labels:
    openshift/cluster-resource-override-admission:
    - allowed_teams:
      - openshift-patch-managers
      - openshift-release-oversight
      - openshift-staff-engineers
      - openshift-sustaining-engineers
      allowed_users:
      - mrunalp
      - joelsmith
      label: backport-risk-assessed
    - allowed_users:
      - asahay19
      - prozehna
      label: cherry-pick-approved
plugins:
  openshift/cluster-resource-override-admission:
    plugins:
    - approve
