label:
  restricted_labels:
    openshift/sriov-tests:
    - allowed_teams:
      - openshift-patch-managers
      - openshift-release-oversight
      - openshift-staff-engineers
      - openshift-sustaining-engineers
      - team-multus-cni-maintainers
      label: backport-risk-assessed
plugins:
  openshift/sriov-tests:
    plugins:
    - approve
