label:
  restricted_labels:
    openshift/oauth-server:
    - allowed_teams:
      - openshift-patch-managers
      - openshift-release-oversight
      - openshift-staff-engineers
      - openshift-sustaining-engineers
      allowed_users:
      - ibihim
      - tkashem
      label: backport-risk-assessed
    - allowed_users:
      - xingxingxia
      - dpuniaredhat
      label: cherry-pick-approved
plugins:
  openshift/oauth-server:
    plugins:
    - approve
