base_images:
  os:
    name: centos
    namespace: openshift
    tag: "7"
binary_build_commands: true
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.13
images:
- from: os
  to: release-controller
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- artifact_dir: /tmp/artifacts
  as: unit
  commands: true
  container:
    from: src
zz_generated_metadata:
  branch: master
  org: openshift
  repo: release-controller-config
