approve:
- commandHelpLink: ""
  repos:
  - openshift/csi-external-snapshot-metadata
  require_self_approval: false
label:
  restricted_labels:
    openshift/csi-external-snapshot-metadata:
    - allowed_teams:
      - openshift-patch-managers
      - openshift-release-oversight
      - openshift-staff-engineers
      - openshift-sustaining-engineers
      allowed_users:
      - dobsonj
      - jsafrane
      - gnufied
      - RomanBednar
      - tsmetana
      - mpatlasov
      label: backport-risk-assessed
lgtm:
- repos:
  - openshift/csi-external-snapshot-metadata
  review_acts_as_lgtm: true
plugins:
  openshift/csi-external-snapshot-metadata:
    plugins:
    - approve
