---
apiVersion: template.openshift.io/v1
kind: Template
parameters:
  - description: The session secret for the component.
    name: SESSION_SECRET
    generate: expression
    from: "[a-zA-Z0-9]{43}"
  - description: "The namespace. Must come from a var or it will get stripped off"
    name: NAMESPACE
    value: ci
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      namespace: ${NAMESPACE}
      name: release-controller-session-secret
    stringData:
      session_secret: "${SESSION_SECRET}="
