kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: release-controller-ocp-priv
  namespace: ci
spec:
  host: openshift-release-priv.apps.ci.l2s4.p1.openshiftapps.com
  tls:
    termination: Reencrypt
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: release-controller-ocp-priv
---
kind: Service
apiVersion: v1
metadata:
  name: release-controller-ocp-priv
  namespace: ci
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: release-controller-priv-tls
spec:
  selector:
    app: release-controller-ocp-priv
  ports:
  - port: 443
    targetPort: 8443
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: release-controller-ocp-priv
  namespace: ci
  annotations:
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"release-controller:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"controller\")].image"}]'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: release-controller-ocp-priv
  template:
    metadata:
      labels:
        app: release-controller-ocp-priv
    spec:
      serviceAccountName: release-controller
      volumes:
      - name: session-secret
        secret:
          secretName: release-controller-session-secret-priv
      - name: internal-tls
        secret:
          secretName: release-controller-priv-tls
      - configMap:
          defaultMode: 420
          name: config
        name: config
      - configMap:
          defaultMode: 420
          name: job-config-misc
        name: job-config-misc
      - configMap:
          defaultMode: 420
          name: job-config-master
        name: job-config-master
      - configMap:
          defaultMode: 420
          name: job-config-3.x
        name: job-config-3x
      - configMap:
          defaultMode: 420
          name: job-config-4.1
        name: job-config-41
      - configMap:
          defaultMode: 420
          name: job-config-4.2
        name: job-config-42
      - configMap:
          defaultMode: 420
          name: job-config-4.3
        name: job-config-43
      - configMap:
          defaultMode: 420
          name: job-config-4.4
        name: job-config-44
      - configMap:
          defaultMode: 420
          name: job-config-4.5
        name: job-config-45
      - name: job-config-46
        configMap:
          name: job-config-4.6
      - name: job-config-47
        configMap:
          name: job-config-4.7
      - name: release-controller-kubeconfigs
        secret:
          secretName: release-controller-kubeconfigs
          items:
          - key: sa.release-controller-ocp-priv.api.ci.config
            path: kubeconfig
      - name: oauth
        secret:
          secretName: github-credentials-openshift-ci-robot
      - name: bugzilla
        secret:
          secretName: bugzilla-credentials-openshift-bugzilla-robot
      - name: plugins
        configMap:
          name: plugins
      containers:
      - name: oauth-proxy
        image: openshift/oauth-proxy:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8443
            name: web
        args:
          - -provider=openshift
          - -https-address=:8443
          - -http-address=
          - -email-domain=*
          - -upstream=http://localhost:8080
          - -client-id=system:serviceaccount:ci:release-controller
          - -openshift-ca=/etc/pki/tls/cert.pem
          - -openshift-ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          - '-openshift-sar={"verb": "get", "resource": "imagestreams", "namespace": "ocp-private"}'
          - '-openshift-delegate-urls={"/": {"verb": "get", "resource": "imagestreams", "namespace": "ocp-private"}}'
          - -client-secret-file=/var/run/secrets/kubernetes.io/serviceaccount/token
          - -cookie-secret-file=/etc/proxy/secrets/session_secret
          - -tls-cert=/etc/tls/private/tls.crt
          - -tls-key=/etc/tls/private/tls.key
        volumeMounts:
          - mountPath: /etc/tls/private
            name: internal-tls
          - mountPath: /etc/proxy/secrets
            name: session-secret
      - name: controller
        image: release-controller:latest
        volumeMounts:
        - mountPath: /etc/config
          name: config
          readOnly: true
        - mountPath: /etc/job-config/misc
          name: job-config-misc
          readOnly: true
        - mountPath: /etc/job-config/master
          name: job-config-master
          readOnly: true
        - mountPath: /etc/job-config/3.x
          name: job-config-3x
          readOnly: true
        - mountPath: /etc/job-config/4.1
          name: job-config-41
          readOnly: true
        - mountPath: /etc/job-config/4.2
          name: job-config-42
          readOnly: true
        - mountPath: /etc/job-config/4.3
          name: job-config-43
          readOnly: true
        - name: job-config-44
          mountPath: /etc/job-config/4.4
          readOnly: true
        - name: job-config-45
          mountPath: /etc/job-config/4.5
          readOnly: true
        - name: job-config-46
          mountPath: /etc/job-config/4.6
          readOnly: true
        - name: job-config-47
          mountPath: /etc/job-config/4.7
          readOnly: true
        - name: release-controller-kubeconfigs
          mountPath: /etc/kubeconfig
          readOnly: true
        - name: oauth
          mountPath: /etc/github
          readOnly: true
        - name: bugzilla
          mountPath: /etc/bugzilla
          readOnly: true
        - name: plugins
          mountPath: /etc/plugins
          readOnly: true
        command:
        - /usr/bin/release-controller
        - --to=release
        - --release-namespace=ocp-priv
        - --prow-config=/etc/config/config.yaml
        - --job-config=/etc/job-config
        - --artifacts=openshift-release-artifacts-priv.svc.ci.openshift.org
        - --listen=127.0.0.1:8080
        - --prow-namespace=ci
        - --non-prow-job-kubeconfig=/etc/kubeconfig/kubeconfig
        - --job-namespace=ci-release-priv
        - --tools-image-stream-tag=4.6:tests
        - -v=6
        - --github-token-path=/etc/github/oauth
        - --github-endpoint=http://ghproxy
        - --github-graphql-endpoint=http://ghproxy/graphql
        - --bugzilla-endpoint=https://bugzilla.redhat.com
        - --bugzilla-api-key-path=/etc/bugzilla/api
        - --plugin-config=/etc/plugins/plugins.yaml
        - --verify-bugzilla
