apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-controller
  namespace: ci
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.ocp-priv: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"release-controller-ocp-priv"}}'
    serviceaccounts.openshift.io/oauth-redirectreference.ocp-s390x-priv: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"release-controller-ocp-s390x-priv"}}'
    serviceaccounts.openshift.io/oauth-redirectreference.ocp-ppc64le-priv: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"release-controller-ocp-ppc64le-priv"}}'
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: release-controller
  namespace: ci
rules:
  - apiGroups:
    - prow.k8s.io
    resources:
    - prowjobs
    verbs:
    - '*'
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: release-controller
  namespace: ci
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: release-controller
subjects:
- kind: ServiceAccount
  name: release-controller
---
# oauth proxy permissions
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: release-controller-priv-oauth
rules:
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: release-controller-priv-oauth
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: release-controller-priv-oauth
subjects:
  - kind: ServiceAccount
    name: release-controller
    namespace: ci
