---
apiVersion: template.openshift.io/v1
kind: Template
parameters:
  - description: The session secret for the ocp-priv release controller's file cache oauth proxy
    name: SESSION_SECRET_PRIV
    generate: expression
    from: "[a-zA-Z0-9]{43}"
  - description: "The namespace. Must come from a var or it will get stripped off"
    name: NAMESPACE_PRIV
    value: ci-release-priv

  - description: The session secret for the ocp-s390x-priv release controller's file cache oauth proxy
    name: SESSION_SECRET_S390X_PRIV
    generate: expression
    from: "[a-zA-Z0-9]{43}"
  - description: "The namespace. Must come from a var or it will get stripped off"
    name: NAMESPACE_S390X_PRIV
    value: ci-release-s390x-priv

  - description: The session secret for the ocp-ppc64le-priv release controller's file cache oauth proxy
    name: SESSION_SECRET_PPC64LE_PRIV
    generate: expression
    from: "[a-zA-Z0-9]{43}"
  - description: "The namespace. Must come from a var or it will get stripped off"
    name: NAMESPACE_PPC64LE_PRIV
    value: ci-release-ppc64le-priv

objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      namespace: ${NAMESPACE_PRIV}
      name: files-cache-session-secret
    stringData:
      session_secret: "${SESSION_SECRET_PRIV}="

  - apiVersion: v1
    kind: Secret
    metadata:
      namespace: ${NAMESPACE_S390X_PRIV}
      name: files-cache-session-secret
    stringData:
      session_secret: "${SESSION_SECRET_S390X_PRIV}="

  - apiVersion: v1
    kind: Secret
    metadata:
      namespace: ${NAMESPACE_PPC64LE_PRIV}
      name: files-cache-session-secret
    stringData:
      session_secret: "${SESSION_SECRET_PPC64LE_PRIV}="
